//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectGUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderLines = new HashSet<OrderLine>();
        }
    
        public int ProductISBN { get; set; }
        public string Title { get; set; }
        public int UnitPrice { get; set; }
        public int YearPublished { get; set; }
        public Nullable<int> QuantityOnHand { get; set; }
        public string Type { get; set; }
        public int Category { get; set; }
        public int PublisherID { get; set; }
        public int AuthorID { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Category Category1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderLine> OrderLines { get; set; }
        public virtual Publisher Publisher { get; set; }
    }
}
